### ISSUE TITLE
Extract all exon sequences

### ISSUE THREAD

**Issue by gernophil** [jeremymcrae/gencodegenes#2]
Hey,

it's me again. I am trying to extract all exon sequences for a given gene, no matter, if they are in the same transcript or not. So, I would need an analog method like `Gencode(gtf_path).canonical.exons`, but for `transcripts`. So something like this: `Gencode(gtf_path).transcripts.exons`. Would that be easy to implement? Happy to help :).

**Comment by jeremymcrae** [comment]
I think this would be possible with the existing code? Each gene has a transcripts attribute, so something like this seems like what you want:

```py
genes = Gencode(gtf_path, fasta_path)
gene = genes[symbol]

for tx in gene.transcripts:
    print(tx.exons)
```

**Comment by gernophil** [comment]
Thanks for your help :). I can confirm this works. Now I just need the `frame` info (see my other question).
